In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt 
import datetime

In [2]:
class Config:
    pass
config = pd.read_pickle('config.pkl')

data_path = '../../kaggleData/JD_logging/'
feature_path = '../../kaggleData/JD_logging/features/'
print(dir(config))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'chi_test_result', 'data_path', 'feature_dict', 'feature_path', 'model_features', 'result_path', 'single_module_validation_indice_set', 'trade_train_size', 'train_2_6_index']

In [3]:
login_tt = pd.read_csv(data_path+'login_tt.csv')
trade_tt_with_recent_logins = pd.read_csv(data_path+'trade_tt_with_recent_3_log_id.csv')
trade_tt = pd.read_csv(data_path+'trade_tt.csv')

login_tt['time'] = login_tt['time'].apply(lambda x : datetime.datetime.strptime(x , '%Y-%m-%d %H:%M:%S'))
trade_tt['time'] = trade_tt['time'].apply(lambda x : datetime.datetime.strptime(x , '%Y-%m-%d %H:%M:%S'))
trade_tt_with_recent_logins['time'] = trade_tt_with_recent_logins['time'].apply(lambda x : datetime.datetime.strptime(x , '%Y-%m-%d %H:%M:%S'))

train_labels = pd.read_pickle(data_path+'trade_train_label.pkl')
trade_tt_with_recent_logins.loc[:config.trade_train_size,'is_risk'] = train_labels

In [4]:
del trade_tt_with_recent_logins['month']
del trade_tt_with_recent_logins['day']
del trade_tt_with_recent_logins['weekday']
del trade_tt_with_recent_logins['hour']
del trade_tt_with_recent_logins['day_cycle']
del trade_tt_with_recent_logins['weekday_cycle']
del trade_tt_with_recent_logins['hour_cycle']
del trade_tt_with_recent_logins['recent_login_id_1']
del trade_tt_with_recent_logins['recent_login_id_2']
trade_wit_last_login_tt = trade_tt_with_recent_logins.merge(login_tt, how = 'left',left_on ='recent_login_id_0',right_on = 'log_id',suffixes=('', '_login'))

In [5]:
trade_wit_last_login_tt

,rowkey,time,id,from,recent_login_id_0,is_risk,log_id,timelong,device,log_from,ip,city,result,timestamp,type,id_login,is_scan,is_sec,time_login,from_login
0,3,2015-01-01 00:00:41,27863,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,6,2015-01-01 00:00:46,115201,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,13,2015-01-01 00:01:02,143711,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,32,2015-01-01 00:03:00,172699,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,43,2015-01-01 00:03:52,53265,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
5,67,2015-01-01 00:05:51,18231,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6,94,2015-01-01 00:10:12,147174,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
7,98,2015-01-01 00:10:48,141674,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
8,116,2015-01-01 00:13:16,105324,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
9,147,2015-01-01 00:19:07,168749,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
10,198,2015-01-01 00:25:51,139034,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
11,282,2015-01-01 00:48:11,157472,train,8.073763e+15,0.0,8.073763e+15,3000.0,851335.0,2.0,111975.0,270.0,1.0,1.420043e+09,3.0,157472.0,False,False,2015-01-01 00:26:18,train
12,287,2015-01-01 00:49:40,144195,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
13,293,2015-01-01 00:50:41,164198,train,6.661234e+14,0.0,6.661234e+14,2000.0,916969.0,2.0,1037643.0,59.0,1.0,1.420043e+09,2.0,164198.0,False,False,2015-01-01 00:20:34,train
14,320,2015-01-01 00:58:28,115201,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
15,343,2015-01-01 01:05:47,87482,train,7.108786e+14,0.0,7.108786e+14,25153.0,902476.0,1.0,1364299.0,438.0,1.0,1.420045e+09,3.0,87482.0,False,False,2015-01-01 01:02:57,train
16,344,2015-01-01 01:05:55,64543,train,5.972875e+15,0.0,5.972875e+15,13687.0,568017.0,1.0,96751.0,78.0,1.0,1.420045e+09,1.0,64543.0,False,False,2015-01-01 00:56:05,train
17,380,2015-01-01 01:17:51,53933,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
18,393,2015-01-01 01:22:20,174789,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
19,419,2015-01-01 01:28:08,162466,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
20,440,2015-01-01 01:40:30,24002,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
21,464,2015-01-01 01:48:43,59616,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
22,472,2015-01-01 01:51:10,120026,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
23,476,2015-01-01 01:52:28,120026,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
24,478,2015-01-01 01:52:39,30357,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
25,503,2015-01-01 02:06:44,48831,train,8.429435e+15,0.0,8.429435e+15,3000.0,697447.0,2.0,763176.0,295.0,1.0,1.420048e+09,3.0,48831.0,False,False,2015-01-01 01:51:18,train
26,506,2015-01-01 02:08:51,61579,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
27,528,2015-01-01 02:33:32,85435,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
28,536,2015-01-01 02:39:07,72922,train,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
29,555,2015-01-01 03:02:01,18138,train,5.175043e+15,1.0,5.175043e+15,9000.0,835072.0,2.0,724987.0,418.0,1.0,1.420052e+09,3.0,18138.0,False,False,2015-01-01 02:59:24,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150564,175943,2015-07-31 22:55:04,40068,test,5.123350e+15,NaN,5.123350e+15,14305.0,148321.0,1.0,925429.0,364.0,1.0,1.438325e+09,1.0,40068.0,False,False,2015-07-31 14:41:14,test
150565,175980,2015-07-31 22:59:48,20713,test,2.676568e+16,NaN,2.676568e+16,4757.0,1070613.0,1.0,1547403.0,237.0,1.0,1.438273e+09,3.0,20713.0,False,False,2015-07-31 00:19:24,test
150566,175983,2015-07-31 23:00:11,63388,test,2.233183e+15,NaN,2.233183e+15,25335.0,133430.0,1.0,76103.0,211.0,1.0,1.437809e+09,1.0,63388.0,False,False,2015-07-25 15:30:16,test
150567,175985,2015-07-31 23:00:22,159008,test,2.571418e+15,NaN,2.571418e+15,20656.0,965535.0,1.0,83139.0,411.0,1.0,1.435399e+09,1.0,159008.0,False,False,2015-06-27 17:57:47,train
150568,176002,2015-07-31 23:02:05,73272,test,5.085450e+15,NaN,5.085450e+15,5105.0,835072.0,1.0,675062.0,63.0,31.0,1.436947e+09,3.0,73272.0,False,False,2015-07-15 15:54:16,test
150569,176011,2015-07-31 23:03:12,49464,test,9.363114e+15,NaN,9.363114e+15,6000.0,257753.0,2.0,998154.0,37.0,1.0,1.434417e+09,3.0,49464.0,False,False,2015-06-16 09:06:22,train
150570,176012,2015-07-31 23:03:16,85583,test,7.209543e+15,NaN,7.209543e+15,14064.0,729102.0,1.0,151321.0,89.0,1.0,1.437103e+09,3.0,85583.0,False,False,2015-07-17 11:16:15,test
150571,176020,2015-07-31 23:03:52,138192,test,4.016543e+15,NaN,4.016543e+15,3.0,907470.0,10.0,1165804.0,21.0,1.0,1.438255e+09,1.0,138192.0,True,False,2015-07-30 19:12:21,test
150572,176029,2015-07-31 23:05:13,171105,test,6.268693e+15,NaN,6.268693e+15,3014.0,45660.0,1.0,890353.0,44.0,1.0,1.438355e+09,1.0,171105.0,False,False,2015-07-31 22:59:14,test
150573,176031,2015-07-31 23:05:28,1086,test,4.581328e+15,NaN,4.581328e+15,8229.0,1017593.0,1.0,120683.0,268.0,1.0,1.438355e+09,1.0,1086.0,False,False,2015-07-31 22:58:55,test
150574,176044,2015-07-31 23:07:05,141953,test,4.110493e+16,NaN,4.110493e+16,5000.0,1069207.0,2.0,170660.0,364.0,1.0,1.424538e+09,3.0,141953.0,False,False,2015-02-22 01:06:35,train
150575,176057,2015-07-31 23:09:07,145704,test,7.341012e+15,NaN,7.341012e+15,7000.0,1066723.0,2.0,470455.0,364.0,1.0,1.438349e+09,3.0,145704.0,False,False,2015-07-31 21:20:09,test
150576,176070,2015-07-31 23:11:13,173862,test,4.313637e+15,NaN,4.313637e+15,3.0,663024.0,10.0,887284.0,283.0,1.0,1.436569e+09,1.0,173862.0,True,False,2015-07-11 07:04:57,test
150577,176073,2015-07-31 23:12:22,165831,test,4.668353e+16,NaN,4.668353e+16,38386.0,936290.0,1.0,605502.0,227.0,1.0,1.438353e+09,3.0,165831.0,False,False,2015-07-31 22:36:43,test
150578,176087,2015-07-31 23:14:47,22563,test,3.782595e+16,NaN,3.782595e+16,11577.0,773584.0,1.0,1131448.0,194.0,1.0,1.438349e+09,3.0,22563.0,False,False,2015-07-31 21:19:54,test
150579,176091,2015-07-31 23:15:05,55776,test,8.253492e+15,NaN,8.253492e+15,46654.0,906213.0,1.0,897248.0,194.0,1.0,1.437318e+09,3.0,55776.0,False,False,2015-07-19 23:07:26,test
150580,176093,2015-07-31 23:15:20,84290,test,1.563058e+16,NaN,1.563058e+16,3.0,1031580.0,10.0,959273.0,492.0,1.0,1.438174e+09,1.0,84290.0,True,False,2015-07-29 20:50:25,test
150581,176100,2015-07-31 23:16:39,18097,test,7.439702e+15,NaN,7.439702e+15,7000.0,455289.0,2.0,165223.0,21.0,1.0,1.437786e+09,3.0,18097.0,False,False,2015-07-25 09:08:01,test
150582,176106,2015-07-31 23:18:22,36795,test,9.986867e+15,NaN,9.986867e+15,7000.0,211688.0,2.0,733026.0,21.0,1.0,1.438353e+09,1.0,36795.0,False,False,2015-07-31 22:30:32,test
150583,176109,2015-07-31 23:18:54,31696,test,4.668255e+15,NaN,4.668255e+15,5000.0,338235.0,2.0,1065462.0,429.0,1.0,1.437783e+09,3.0,31696.0,False,False,2015-07-25 08:10:56,test
150584,176116,2015-07-31 23:19:46,18097,test,7.439702e+15,NaN,7.439702e+15,7000.0,455289.0,2.0,165223.0,21.0,1.0,1.437786e+09,3.0,18097.0,False,False,2015-07-25 09:08:01,test
150585,176149,2015-07-31 23:24:31,23927,test,7.431117e+15,NaN,7.431117e+15,14799.0,99895.0,1.0,1428669.0,211.0,1.0,1.437889e+09,1.0,23927.0,False,False,2015-07-26 13:29:21,test
150586,176154,2015-07-31 23:25:23,91163,test,7.625944e+15,NaN,7.625944e+15,20641.0,1008906.0,1.0,1246147.0,194.0,1.0,1.435540e+09,3.0,91163.0,False,False,2015-06-29 08:59:51,train
150587,176176,2015-07-31 23:29:19,92356,test,5.908730e+15,NaN,5.908730e+15,9000.0,676814.0,2.0,457632.0,238.0,1.0,1.428464e+09,3.0,92356.0,False,False,2015-04-08 11:28:01,train
150588,176190,2015-07-31 23:32:40,157816,test,6.074461e+15,NaN,6.074461e+15,5.0,106263.0,10.0,1001462.0,211.0,1.0,1.437537e+09,1.0,157816.0,True,False,2015-07-22 11:54:50,test
150589,176212,2015-07-31 23:39:57,13337,test,8.685467e+15,NaN,8.685467e+15,7000.0,1049385.0,2.0,446753.0,364.0,1.0,1.438185e+09,1.0,13337.0,False,False,2015-07-29 23:57:30,test
150590,176231,2015-07-31 23:44:21,116533,test,6.490094e+15,NaN,6.490094e+15,5487.0,676869.0,1.0,731725.0,42.0,1.0,1.438357e+09,1.0,116533.0,False,False,2015-07-31 23:40:57,test
150591,176243,2015-07-31 23:46:52,48369,test,7.315921e+15,NaN,7.315921e+15,6000.0,215410.0,2.0,1415482.0,222.0,1.0,1.438345e+09,3.0,48369.0,False,False,2015-07-31 20:23:16,test
150592,176271,2015-07-31 23:55:58,7677,test,9.576906e+15,NaN,9.576906e+15,5000.0,551419.0,2.0,1180392.0,302.0,1.0,1.438179e+09,1.0,7677.0,False,False,2015-07-29 22:14:10,test
150593,176288,2015-07-31 23:58:30,135870,test,2.643765e+15,NaN,2.643765e+15,9356.0,704269.0,1.0,376618.0,488.0,1.0,1.438274e+09,3.0,135870.0,False,False,2015-07-31 00:35:00,test

In [6]:
test_row = trade_wit_last_login_tt.iloc[45050]

In [7]:
def find_related_hcc_trades_before(row,trade_table,hcc,*args,**kw):
    related_trades = trade_table[trade_table[hcc] == row[hcc]]
    related_trades_before = related_trades[related_trades['time']<row.time]
    return related_trades_before    

def get_mult_hcc_target_encoding(idx_row_tuple,trade_table,hcc_list):
    idx = idx_row_tuple[0]
    row = idx_row_tuple[1]
    result_dict= {}
        
    for feature in hcc_list:
        result_dict[feature+'_t_encoding'] = np.mean(find_related_hcc_trades_before(row,trade_table,feature)['is_risk'].dropna())
    return (idx,row.rowkey,result_dict)

In [8]:
get_mult_hcc_target_encoding((45050,test_row),trade_wit_last_login_tt,['id','ip','device','city'])

(45050,
 628290,
 {'city_t_encoding': 0.015706806282722512,
  'device_t_encoding': 0.0,
  'id_t_encoding': 0.0,
  'ip_t_encoding': 0.0})

### make new hcc features by combining

In [9]:
trade_wit_last_login_tt['ip_id']  = trade_wit_last_login_tt.apply(lambda x : str((x.ip,x.id)),axis = 1)
trade_wit_last_login_tt['ip_device']  = trade_wit_last_login_tt.apply(lambda x : str((x.ip,x.device)),axis = 1)
trade_wit_last_login_tt['city_id']  = trade_wit_last_login_tt.apply(lambda x : str((x.city,x.id)),axis = 1)
trade_wit_last_login_tt['city_device']  = trade_wit_last_login_tt.apply(lambda x : str((x.city,x.device)),axis = 1)
trade_wit_last_login_tt['device_id']  = trade_wit_last_login_tt.apply(lambda x : str((x.id,x.device)),axis = 1)

In [10]:
print(trade_wit_last_login_tt.shape)
print(len(trade_wit_last_login_tt['ip_id'].unique()))
print(len(trade_wit_last_login_tt['ip_device'].unique()))
print(len(trade_wit_last_login_tt['city_id'].unique()))
print(len(trade_wit_last_login_tt['city_device'].unique()))
print(len(trade_wit_last_login_tt['device_id'].unique()))

(150594, 25)
66793
67401
39937
50917
54393

In [11]:
trade_wit_last_login_tt['device_id_ip']  = trade_wit_last_login_tt.apply(lambda x : str((x.id,x.device,x.ip)),axis = 1)
trade_wit_last_login_tt['device_id_city']  = trade_wit_last_login_tt.apply(lambda x : str((x.id,x.device,x.city)),axis = 1)
print(len(trade_wit_last_login_tt['device_id_ip'].unique()))
print(len(trade_wit_last_login_tt['device_id_city'].unique()))

71027
57476

### Generating new features with spark

In [12]:
import pyspark as spark

conf = spark.SparkConf().setAppName('jupyter_backend').setMaster('local[12]')\
        .set('spark.executor.memory','2g')\
        .set('spark.default.parallelism','112')
sc = spark.SparkContext(conf=conf)

In [13]:
#parallel computing
hcc_list = ['ip_device','ip_id','device_id','city_id','device_id_city']+['id','ip','device','city']

trade_tt_rdd_buffer = []
for (idx,row) in trade_wit_last_login_tt.iterrows():
    trade_tt_rdd_buffer.append((idx,row))
trade_tt_rdd = sc.parallelize(trade_tt_rdd_buffer)

#result_rdd = trade_tt_rdd.map(lambda idx_row_tuple : get_mult_hcc_target_encoding(idx_row_tuple,trade_wit_last_login_tt,['id','ip','device']))
result_rdd = trade_tt_rdd.map(lambda idx_row_tuple : get_mult_hcc_target_encoding(idx_row_tuple,trade_wit_last_login_tt,hcc_list))

result_rdd_buffer = result_rdd.collect()

In [14]:
result_rdd_to_df_buffer = []
for ori_id,rowkey,result_dict in result_rdd_buffer:
    unit_dict= result_dict
    unit_dict['ori_id'] = ori_id
    unit_dict['rowkey'] = rowkey
    
    result_rdd_to_df_buffer.append(unit_dict)

result_df = pd.DataFrame(result_rdd_to_df_buffer)

assert (np.sum(result_df['rowkey']!=trade_tt['rowkey']))==0
assert (np.sum(result_df['ori_id']!=trade_tt.index))==0

In [15]:
result_df = result_df.fillna(0)

In [16]:
del result_df['rowkey']
del result_df['ori_id']
trade_tt = pd.concat([trade_tt,result_df],axis = 1)
print(trade_tt.shape)

(150594, 13)

In [17]:
original_hcc_encoding = ['city_t_encoding', 'device_t_encoding', 'id_t_encoding', 'ip_t_encoding']
new_hcc_encodin_double_combining = ['ip_device_t_encoding','ip_id_t_encoding','device_id_t_encoding','city_id_t_encoding','device_id_city_t_encoding']

In [19]:
trade_tt.shape

(150594, 13)

In [24]:
#get random mask for the encoding features
np.random.seed(242)
random_mask = np.random.uniform(-0.1,0.1,150594)+1

In [26]:
for feature in original_hcc_encoding+new_hcc_encodin_double_combining:
    trade_tt[feature] = trade_tt[feature]*random_mask

In [28]:
for feature in original_hcc_encoding+new_hcc_encodin_double_combining:
    pd.to_pickle(trade_tt[feature].values,feature_path+feature+'.pkl')

In [ ]:
config.feature_dict.keys()

In [ ]:
config.feature_dict['hcc_target_encoding'] = original_hcc_encoding
config.feature_dict['hcc_mult_target_encoding'] = new_hcc_encodin_double_combining

In [ ]:
pd.to_pickle(config,'config.pkl')